export const SITE = {
  name: 'Ringdove',
  legalName: 'RINGDOVE SP. Z O.O.',
  url: 'https://ringdove.studio',
  description:
    'A craft-led design studio for product interfaces and audio plugin design. Two disciplines, one standard.',
  email: 'hello@ringdove.studio',
  location: 'Kraków, Poland',
  coords: '50.0647° N · 19.9450° E',
  colophon: 'Set in Times & Author · MMXXVI',
  side: {
    left: 'A design studio · Currently designing for Polyphon & Lattice · Open for Q3',
    right: 'Located in Kraków · CET · Working remotely · Issue Nº 04 · Spring 2026',
  },
  hero: {
    headline: 'Quiet design for digital products that <em>repay attention.</em>',
    caption: 'Two disciplines, <em>one standard.</em>',
  },
  contact: {
    write: { sub: 'For new work or a quiet conversation.' },
    located: { sub: 'CET · Working remotely.' },
    currently: { headline: 'Open for Q3', sub: 'Two slots, both tracks.' },
  },
  disciplines: {
    product: {
      slug: 'product',
      kicker: 'Discipline I',
      title: 'Digital Product <em>Design.</em>',
      titlePlain: 'Digital Product Design',
      cardTitle: 'Digital Product <em>Design</em>',
      lead: 'Identity, product surface, and the design system underneath, for software founders building considered products.',
      body: 'We work end to end from first sketches through the design system that keeps the product coherent as it grows. <em>We want to be useful early, when the decisions matter most.</em>',
      scope: 'Identity · Product surface · Design system · Marketing site. Three to six months, embedded.',
      deliver: 'Identity · Product surface · Design system · Marketing site',
      term: 'Three to six months, embedded',
      cta: 'See selected product work',
      emailSubject: 'Digital product inquiry',
      currentlyHeadline: 'Open for Q3',
      currentlySub: 'One product engagement open this cycle.',
    },
    audio: {
      slug: 'audio',
      kicker: 'Discipline II',
      title: 'Audio Software <em>Design.</em>',
      titlePlain: 'Audio Software Design',
      cardTitle: 'Audio Software <em>Design</em>',
      lead: 'Plugin and host interfaces, brand, and packaging for plugin developers and audio software companies.',
      body: 'We design plugin interfaces that respect the workflow of the people using them, with brand and packaging that <em>gives the plugin a place in the room.</em>',
      scope: 'Plugin GUI · Brand · Packaging · Marketing site · Manual. Six to twelve weeks per plugin.',
      deliver: 'Plugin GUI · Brand · Packaging · Marketing site · Manual',
      term: 'Six to twelve weeks per plugin',
      cta: 'See selected audio work',
      emailSubject: 'Audio software inquiry',
      currentlyHeadline: 'Open for Q3',
      currentlySub: 'One audio engagement open this cycle.',
    },
  },
} as const;

export const ROMAN: Record<number, string> = {
  1: 'I',
  2: 'II',
  3: 'III',
  4: 'IV',
  5: 'V',
  6: 'VI',
  7: 'VII',
  8: 'VIII',
  9: 'IX',
  10: 'X',
};
